version: '3.1'

services:

  db:
    image: postgres:10-alpine
    restart: always
    container_name: pg_10
    hostname: pg_10
    environment:
      POSTGRES_PASSWORD: QRdffq4312
      TZ: 'America/Guatemala'
      PGTZ: 'America/Guatemala'
    ports:
      - 5433:5432

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment: 
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - 8080:80
